# Generated by Django 6.0.7 on 2026-07-09 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('degree_pt', models.CharField(max_length=200)),
                ('degree_en', models.CharField(max_length=200)),
                ('period_start', models.CharField(max_length=20)),
                ('period_end', models.CharField(max_length=20)),
                ('details_pt', models.JSONField(default=list)),
                ('details_en', models.JSONField(default=list)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Education entries',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('role_pt', models.CharField(max_length=200)),
                ('role_en', models.CharField(max_length=200)),
                ('period_start', models.CharField(max_length=20)),
                ('period_end', models.CharField(help_text="e.g. 'presente' / 'present'", max_length=20)),
                ('context_pt', models.CharField(blank=True, max_length=300)),
                ('context_en', models.CharField(blank=True, max_length=300)),
                ('highlights_pt', models.JSONField(default=list, help_text='List of bullet strings')),
                ('highlights_en', models.JSONField(default=list)),
                ('tools', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Experience entries',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Bruno Mingoti', max_length=120)),
                ('headline_pt', models.CharField(max_length=200)),
                ('headline_en', models.CharField(max_length=200)),
                ('bio_pt', models.TextField()),
                ('bio_en', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('scholar_url', models.URLField(blank=True)),
                ('cv_pt_file', models.FileField(blank=True, upload_to='cv/')),
                ('cv_en_file', models.FileField(blank=True, upload_to='cv/')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(blank=True, max_length=300)),
                ('venue', models.CharField(help_text='e.g. SIBGRAPI 2025', max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('paper', 'Paper / conference'), ('thesis', 'Thesis / TCC'), ('report', 'Technical report')], default='paper', max_length=20)),
                ('url', models.URLField(blank=True, help_text='Zenodo / DOI / repository link')),
                ('summary_pt', models.TextField(blank=True)),
                ('summary_en', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_pt', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('summary_pt', models.CharField(help_text='Short teaser shown on the gallery card', max_length=280)),
                ('summary_en', models.CharField(max_length=280)),
                ('body_pt', models.TextField(help_text='Full case study, markdown supported')),
                ('body_en', models.TextField()),
                ('role_pt', models.CharField(blank=True, max_length=200)),
                ('role_en', models.CharField(blank=True, max_length=200)),
                ('period_start', models.CharField(blank=True, help_text='e.g. 2024-08', max_length=20)),
                ('period_end', models.CharField(blank=True, help_text="e.g. 2025-12 or 'presente'", max_length=20)),
                ('tools', models.CharField(blank=True, help_text='Comma-separated: Python, OpenCV, ...', max_length=300)),
                ('icon', models.CharField(default='ti-code', help_text='Tabler icon name, e.g. ti-cpu', max_length=60)),
                ('cover_image', models.ImageField(blank=True, upload_to='projects/')),
                ('repo_url', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='content.institution')),
            ],
            options={
                'ordering': ['order', '-period_start'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption_pt', models.CharField(blank=True, max_length=200)),
                ('caption_en', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
