# Generated by Django 6.0.7 on 2026-07-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceentry',
            name='recommendation_letter',
            field=models.FileField(blank=True, help_text='PDF or image of the recommendation letter for this role, shown as an inline preview.', upload_to='recommendations/'),
        ),
    ]
