# Generated by Django 6.0.7 on 2026-07-09 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_experienceentry_recommendation_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experienceentry',
            name='recommendation_letter',
        ),
        migrations.CreateModel(
            name='RecommendationLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='PDF or image of the letter.', upload_to='recommendations/')),
                ('label_pt', models.CharField(blank=True, help_text="e.g. 'Carta — Fulano de Tal'. Leave blank to auto-number.", max_length=150)),
                ('label_en', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_letters', to='content.experienceentry')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
